### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by 49694445** [tangzx/IntelliJ-EmmyLua#9]
Method com/tang/intellij/lua/codeInsight/LuaParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract

Method com/tang/intellij/lua/codeInsight/LuaParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
java.lang.AbstractMethodError: Method com/tang/intellij/lua/codeInsight/LuaParameterHintsProvider.getHintInfo(Lcom/intellij/psi/PsiElement;)Lcom/intellij/codeInsight/hints/HintInfo; is abstract
	at com.tang.intellij.lua.codeInsight.LuaParameterHintsProvider.getHintInfo(LuaParameterHintsProvider.java)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.process(ParameterHintsPassFactory.java:122)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.lambda$doCollectInformation$2(ParameterHintsPassFactory.java:94)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.intellij.codeInsight.hints.ParameterHintsPassFactory$ParameterHintsPass.doCollectInformation(ParameterHintsPassFactory.java:94)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by 49694445** [comment]
不过貌似不影响使用

**Comment by tangzx** [comment]
用错了版本，你在IDEA2017上用了LuaIDE 2016的版本，重新下载带IDEA171字眼的插件zip安装
